name: Create Integration EKS Full Environment 

on: 
  push:
    branches:
      - main
jobs:
  plan:
    runs-on: ubuntu-latest
         
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.HELIOS_INT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HELIOS_INT_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: secrets

      - name: Terraform plan
        run : terraform plan -out=plan.tfplan
        working-directory: secrets

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: secrets/plan.tfplan   

  apply:
    needs: plan
    if: success()
    runs-on: ubuntu-latest
         
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HELIOS_INT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HELIOS_INT_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Configure AWS CLI
        run: aws configure set default.region us-east-1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: secrets

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: terraform apply --auto-approve secrets/plan.tfplan
        working-directory: secrets
        
